import axios from 'axios';
import { HostawayReviewResponse, HostawayReview, Review } from './types';
import { REVIEW_SOURCES, REVIEW_TYPES, REVIEW_STATUSES } from './constants';
import { generatePropertyId } from './utils';

const HOSTAWAY_API_KEY = process.env.HOSTAWAY_API_KEY!;
const HOSTAWAY_ACCOUNT_ID = process.env.HOSTAWAY_ACCOUNT_ID!;
const HOSTAWAY_BASE_URL = process.env.HOSTAWAY_BASE_URL!;

/**
 * Hostaway API client for fetching and normalizing review data
 */
export class HostawayAPI {
  private readonly client = axios.create({
    baseURL: HOSTAWAY_BASE_URL,
    headers: {
      'Authorization': `Bearer ${HOSTAWAY_API_KEY}`,
      'Content-Type': 'application/json',
    },
    timeout: 10000, // 10 second timeout
  });

  /**
   * Fetch reviews from Hostaway API
   * @returns Promise resolving to array of Hostaway reviews
   * @throws Error if API request fails
   */
  async getReviews(): Promise<HostawayReview[]> {
    try {
      const response = await this.client.get<HostawayReviewResponse>('/reviews', {
        params: {
          accountId: HOSTAWAY_ACCOUNT_ID,
        },
      });

      if (response.data.status === 'success') {
        return response.data.result;
      } else {
        throw new Error(`Hostaway API error: ${response.data.status}`);
      }
    } catch (error) {
      console.error('Error fetching Hostaway reviews:', error);
      throw error;
    }
  }

  /**
   * Normalize a Hostaway review to our internal Review format
   * @param hostawayReview Raw review data from Hostaway API
   * @returns Normalized review data ready for database storage
   */
  normalizeReview(hostawayReview: HostawayReview): Omit<Review, 'id' | 'createdAt' | 'updatedAt'> {
    return {
      source: REVIEW_SOURCES.HOSTAWAY,
      type: hostawayReview.type as typeof REVIEW_TYPES[keyof typeof REVIEW_TYPES],
      status: hostawayReview.status as typeof REVIEW_STATUSES[keyof typeof REVIEW_STATUSES],
      rating: hostawayReview.rating,
      overallRating: hostawayReview.rating || undefined,
      publicReview: hostawayReview.publicReview,
      privateReview: undefined,
      submittedAt: new Date(hostawayReview.submittedAt),
      guestName: hostawayReview.guestName,
      propertyId: generatePropertyId(hostawayReview.listingName),
      propertyName: hostawayReview.listingName,
      isApprovedForPublic: false, // Reviews require manager approval by default
      managerNotes: undefined,
      categories: hostawayReview.reviewCategory.map(cat => ({
        id: '', // Will be generated by Prisma
        reviewId: '', // Will be set when saving
        category: cat.category,
        rating: cat.rating,
      })),
    };
  }
}

// Mock data for fallback when API has no reviews
export const mockHostawayReviews: HostawayReview[] = [
  {
    id: 7453,
    type: "guest-to-host",
    status: "published",
    rating: 9,
    publicReview: "Amazing stay! The property was clean, well-located, and the host was very responsive. Would definitely recommend and stay again.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "location", rating: 9 },
      { category: "value", rating: 8 }
    ],
    submittedAt: "2024-08-21 22:45:14",
    guestName: "Sarah Johnson",
    listingName: "2B N1 A - 29 Shoreditch Heights"
  },
  {
    id: 7454,
    type: "guest-to-host",
    status: "published",
    rating: 8,
    publicReview: "Great location and clean apartment. The check-in process was smooth. Only minor issue was the Wi-Fi was a bit slow, but overall excellent stay.",
    reviewCategory: [
      { category: "cleanliness", rating: 9 },
      { category: "communication", rating: 8 },
      { category: "location", rating: 10 },
      { category: "value", rating: 7 }
    ],
    submittedAt: "2024-08-19 14:30:22",
    guestName: "Michael Chen",
    listingName: "1B E2 B - 45 Canary Wharf Tower"
  },
  {
    id: 7455,
    type: "guest-to-host",
    status: "published",
    rating: 10,
    publicReview: "Perfect stay! Everything was exactly as described. The apartment is modern, spotlessly clean, and in an excellent location. Host was super helpful.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 10 },
      { category: "location", rating: 10 },
      { category: "value", rating: 10 }
    ],
    submittedAt: "2024-08-18 09:15:33",
    guestName: "Emma Thompson",
    listingName: "Studio S3 - 12 Kings Cross Central"
  },
  {
    id: 7456,
    type: "guest-to-host",
    status: "published",
    rating: 6,
    publicReview: "The location was good and the apartment was clean, but there were some maintenance issues. The heating wasn't working properly and it took a while to get resolved.",
    reviewCategory: [
      { category: "cleanliness", rating: 8 },
      { category: "communication", rating: 6 },
      { category: "location", rating: 9 },
      { category: "value", rating: 5 }
    ],
    submittedAt: "2024-08-17 16:45:12",
    guestName: "James Wilson",
    listingName: "2B N1 A - 29 Shoreditch Heights"
  },
  {
    id: 7457,
    type: "guest-to-host",
    status: "published",
    rating: 9,
    publicReview: "Wonderful experience! The apartment exceeded expectations. Modern amenities, great location near transport links, and excellent customer service.",
    reviewCategory: [
      { category: "cleanliness", rating: 10 },
      { category: "communication", rating: 9 },
      { category: "location", rating: 10 },
      { category: "value", rating: 8 }
    ],
    submittedAt: "2024-08-15 11:20:45",
    guestName: "Lisa Garcia",
    listingName: "1B E2 B - 45 Canary Wharf Tower"
  }
];

export const hostawayAPI = new HostawayAPI();
