services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - app_data:/app/data

volumes:
  app_data:
